### ISSUE TITLE
On iPhone 6s+ device, the background color of the last button doesn't fit the entire button space

### ISSUE THREAD

**Issue by skypanther** [skypanther/SegmentedControl#5]
![slack_for_ios_upload_720](https://cloud.githubusercontent.com/assets/507996/13324413/a15e50f0-dbab-11e5-9353-0df4a4d8c1bb.jpg)

It has been reported to me that on an iPhone 6s+ device, the last button's background color won't fill the entire space. The graphic above is a crop of the screenshot sent to me in that report. However, on the simulator, it works as intended. I need to get my hands on a device to resolve this.

The example app included with the repo should be sufficient for testing/reproducing the issue.

**Comment by WillDent** [comment]
@skypanther I will take a look.

**Comment by skypanther** [comment]
Resolved by PR #6
